### PR TITLE
Check for Windows OS or JULIA_COPY_STACKS on jcall, improve testing

### PR DESCRIPTION
**Pull request by mkitti**
Squashed commit of the following:

commit 8dbbcdcbd66c5f86cf8b5be05f45d92b56f128f5
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Fri Mar 6 21:29:18 2020 -0600

    Enable JULIA_COPY_STACKS=0 on mac

commit b9b89ee385ffd8af9e07889af0b75191f4f891de
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Fri Mar 6 19:43:35 2020 -0600

    Reduce testing

commit 21b01981e35b9b7536e0e1edd2a7ae492bb66074
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Fri Mar 6 17:58:42 2020 -0600

    Configure forced async tests

commit c9c3051f71619ea012cb50bd44189a5890043fc7
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Fri Mar 6 17:39:43 2020 -0600

    Don't expect exception on Windows

commit 2df1c844f0d329b6e3e43f8181fb797bc2655f27
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Fri Mar 6 17:29:35 2020 -0600

    Create new environment test flags, check async fail on windows

commit 56abdf68b8b265b4aa6c43a2e7fbcca5a7bdcdd0
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Mon Feb 24 03:35:43 2020 -0600

    Include but allow to fail linux @async case with JULIA_COPY_STACKS=0

commit 0c0279cbd0dd91ac0be2f69683a9108dd17d41ed
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Mon Feb 24 03:14:16 2020 -0600

    Do not initialize using @async on Windows

commit dfc4aea3382bbed379a49129e0ac8a1129621ce7
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Mon Feb 24 03:05:19 2020 -0600

    Test JavaCall under @async

commit 7ebf526b2a7ec87fd5b7d95114dcd4a82596ed1f
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Mon Feb 24 02:26:55 2020 -0600

    Streamline Travis configuration, include Windows

commit bc2431df350e51e3fcf201844aee26af10d73eab
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Mon Feb 24 01:39:05 2020 -0600

    JULIA_COPY_STACKS should not be recommended or asserted on Windows

commit 59973a37a91343dd62b3e0fc39737964e91f135a
Author: Mark Kittisopikul <mark.kittisopikul@utsouthwestern.edu>
Date:   Tue Feb 18 11:23:49 2020 -0600

    Assert root Task for jcall and jfield

### CODE REVIEW

**Comment by mkitti** [comment]
`JULIA_COPY_STACKS=1` does not seem to work well on Windows, so we should not recommend setting that environmental variable on that operating system.

**Comment by mkitti** [comment]
Users are finding that `JULIA_COPY_STACKS=1` does not work on Windows:
https://discourse.julialang.org/t/problem-in-running-julia-on-juno/35412/2

**Comment by aviks** [comment]
Is there any change needed to the documentation based on this PR?

**Comment by mkitti** [comment]
I added some documentation for using JavaCall on Windows.

**Pull request merged**
