### PR TITLE
WIP: Assert root Task for jcall and jfield

### PR DESCRIPTION
**Pull request by mkitti**
Work in progress on expanding assertions throughout the API. I targeted exported functions which may return incorrect results or strange errors such as "java.lang.System is not found".

### CODE REVIEW

**Comment by aviks** [comment]
Eventually everything goes thru the two `_jcall` methods, I think.

**Comment by mkitti** [comment]
`JavaCall` might be working better on Windows than Linux. Before proceeding further, we should expand the tests further to see what is working under `@async`

**Comment by mkitti** [comment]
`JULIA_COPY_STACKS` does not seem to work well on Windows and `JavaCall` seems to work well without it. https://travis-ci.org/mkitti/JavaCall.jl/builds/654273171

It may be necessary to qualify the use of `JULIA_COPY_STACKS` for Linux and Mac only.

**Comment by aviks** [comment]
Did you mean to close this?

**Comment by mkitti** [comment]
Yes, I think the assertions may prevent operation on Windows, so I am expanding testing. I will probably rename the assertion to something more general before resubmitting a PR.
Current progress: https://github.com/mkitti/JavaCall.jl/tree/test_async 
Testing: https://travis-ci.org/mkitti/JavaCall.jl/builds/654326201

**Pull request closed without merging**
