### PR TITLE
2D arrays, better handling of 1D arrays of primitive types

### PR DESCRIPTION
**Pull request by dfdx**
Added support for 2D arrays and fixed a few issues with 1D arrays. In particular, now it's possible to write:

```
# double[] testDoubleArray()
jcall(T, "testDoubleArray", Array{jdouble,1}, ())  # ==> Vector{Float64}

# double[][] testDoubleArray2D - interpret as either vector of vectors or a matrix
jcall(T, "testDoubleArray2D", Array{Array{jdouble, 1},1}, ()) # ==> Vector{Vector{Float64}}
jcall(T, "testDoubleArray2D", Array{jdouble,2}, ())           # ==> Matrix{Float64}

# String[][] testStringArray2D (or any JavaObject in general)
jcall(T, "testStringArray2D", Array{JString,2}, ())   # ==> 2x2 array of JString
```
I don't see the need to support 3D and larger-dimensional arrays for several reasons:

 * even with the current approach it's possible to extract all the data down to the element level using nested `Vector{Vector{...}}` type
 * I've never seen a sane Java developer using more than 2 levels of arrays :)
 * if we encounter such a case, it makes sense to create a dedicated `JavaNDArray <: AbstractArray` type and not to copy data to Julia memory at all

### CODE REVIEW

**Comment by dfdx** [comment]
Just noticed that tests are failing because of missing classes. Will check it tomorrow.

**Comment by dfdx** [comment]
Something weird is going on here: after updating the `Test.java`, recompiling it on my machine and uploading to the server, Travis complains with the `ClassNotFound`. I have checked that: 

 * tests pass on my local machine
 * classpath hasn't been changed
 * putting `*.class` files from the master fixes the issue on Travis

Of course, to finish this PR I need the new versions of `*.class` files on Github/Travis.

@aviks Maybe there's something I'm missing in this pipeline?

**Comment by aviks** [comment]
The travis tests are being run with JDK 7. Are your compiled files compatible with 7, or are they 8 only?  Not sure if that is the cause, just guessing.

**Comment by dfdx** [comment]
You nailed it! Everything works fine now.

**Comment by aviks** [comment]
Looks good, thanks! Makes sense to add a few lines to the docs?

**Comment by dfdx** [comment]
Good point. Added some docs.

**Pull request merged**
